### PR TITLE
fix SSR issue caused by useSyncExternalStore

### PR DESCRIPTION
**Pull request by muhajirdev**
## Summary

#181 

## How did you test this change?

- Tested it on my local, the error disappear

### CODE REVIEW

**Comment by jamesgpearce** [comment]
Amazing! Thank you. Let me try and get this into the next release.

**Comment by jamesgpearce** [comment]
I brought this into the beta branch ready for the 5.3 release. Thanks!

**Comment by jamesgpearce** [comment]
Shipped in v5.3.0-beta.3 - [check it out](https://beta.tinybase.org/guides/releases/#v5-3)!

**Comment by muhajirdev** [comment]
AWESOME! Thank you!

**Pull request closed without merging**
